# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BoxingTimer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BoxingTimer
	pod 'SnapKit'
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'ReactorKit'
	pod 'RxViewController'
	pod 'Then'
	pod 'RxDataSources'

end
